name: eye_of_sauron_flutter
description: "An experimental sample of Eye of Sauron particle effects."
version: 1.0.0
repository: https://github.com/vjm-dev/eye_of_sauron_flutter

environment:
  sdk: ">=3.8.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
